backend:
  name: git-gateway
  branch: master

display_url: https://www.showalter.family

media_folder: "assets/images"

collections:
  - name: "journal"
    label: "Journal"
    folder: "posts"
    create: true
    slug: "{{month}}-{{day}}-{{year}}.md"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "{{slug}}" hidden: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
