backend:
  name: git-gateway
  branch: master

display_url: https://www.showalter.family

media_folder: "assets/images"

collections:
  - name: "journal"
    label: "Journal"
    folder: "posts"
    create: true
    slug: "{{fields.date}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "site_data"
    label: "Site Data"
    files:
      - name: "recipe_index"
        label: "Recipe Index"
        delete: false
        file: "_data/recipe_toc.json"
        fields:
          - {label: "Recipe Tags", name: "recipe_tags", widget: "list", allow_add: true, field: {label: "Tag", name: "tag", widget: "string"}}
  - name: "recipes"
    label: "Recipes"
    folder: "recipes"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/recipe.njk"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, field: {label: "Tag", name: "tag", widget: "string"}, required: true}
      - {label: "Ingredients", name: "ingredients", widget: "list", allow_add: true, field: {label: "Ingredient", name: "single_ingredient", widget: "string"}, required: true}
      - {label: "Method", name: "method", widget: "markdown", required: true}
      - {label: "Source", name: "source", widget: "markdown", required: false}
