backend:
  name: git-gateway
  branch: master

display_url: https://www.showalter.family

media_folder: "assets/images"

collections:
  - name: "journal"
    label: "Journal"
    identifier_field: "date"
    folder: "posts"
    create: true
    slug: "{{month}}-{{day}}-{{year}}"
    fields:
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "LLLL", timeFormat: false, required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
