backend:
  name: git-gateway
  branch: master

display_url: https://www.showalter.family

media_folder: "assets/images"

collections:
  - name: "site_data"
    label: "Site Data"
    files:
      - name: "recipe_index"
        label: "Recipe Index"
        delete: false
        file: "_data/recipe_toc.json"
        fields:
          - {label: "Recipe Tags", name: "recipe_tags", widget: "list", allow_add: true, field: {label: "Tag", name: "tag", widget: "string"}}
      - name: "garden"
        label: "Garden"
        delete: false
        file: "_data/garden.json"
        fields:
          - label: "Plants"
            name: "plants"
            widget: "list"
            allow_add: true
            fields:
              - label: "Plant"
                name: "plant"
                widget: "string"
              - label: "Variety"
                name: "variety"
                widget: "string"
              - label: "Planted on"
                name: "planted_on"
                widget: "datetime"
                format: "YYYY-MM-DD"
              - label: "Expected harvest"
                name: "expected_harvest"
                widget: "datetime"
                format: "YYYY-MM-DD"
  - name: "recipes"
    label: "Recipes"
    folder: "recipes"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/recipe.njk"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, field: {label: "Tag", name: "tag", widget: "string"}, required: true}
      - {label: "Ingredients", name: "ingredients", widget: "list", allow_add: true, field: {label: "Ingredient", name: "single_ingredient", widget: "string"}, required: true}
      - {label: "Method", name: "method", widget: "markdown", required: true}
      - {label: "Source", name: "source", widget: "markdown", required: false}
  - name: "garden"
    label: "Garden Updates"
    label_singular: "Garden Update"
    folder: "garden"
    create: true
    slug: "{{fields.date}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/garden.njk"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, field: {label: "Tag", name: "tag", widget: "string"}, required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}